// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface HearthstoneMetadata {
  sets: Set[];
  setGroups: SetGroup[];
  gameModes: Generic[];
  arenaIds: number[];
  types: Generic[];
  rarities: Rarity[];
  classes: Class[];
  minionTypes: Generic[];
  spellSchools: Generic[];
  mercenaryRoles: Generic[];
  mercenaryFactions: Generic[];
  keywords: Keyword[];
  filterableFields: string[];
  numericFields: string[];
  cardBackCategories: Generic[];
}

export interface Generic {
  slug: string;
  id: number;
  name: string;
  gameModes?: number[];
}

export interface Class {
  slug: string;
  id: number;
  name: string;
  cardId?: number;
  heroPowerCardId?: number;
  alternateHeroCardIds?: number[];
}

export interface Keyword {
  id: number;
  slug: string;
  name: string;
  refText: string;
  text: string;
  gameModes: number[];
}

export interface Rarity {
  slug: string;
  id: number;
  craftingCost: Array<number | null>;
  dustValue: Array<number | null>;
  name: string;
}

export interface SetGroup {
  slug: string;
  year?: number;
  svg?: null | string;
  cardSets: string[];
  name: string;
  standard?: boolean;
  icon?: string;
  yearRange?: string;
}

export interface Set {
  id: number;
  name: string;
  slug: string;
  hyped: boolean;
  type: SetType;
  collectibleCount: number;
  collectibleRevealedCount: number;
  nonCollectibleCount: number;
  nonCollectibleRevealedCount: number;
  aliasSetIds?: number[];
}

export enum SetType {
  Adventure = "adventure",
  Base = "base",
  Empty = "",
  Expansion = "expansion"
}
